django_project/urls.py
from . import views

"""django_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('contents/', include('contents.urls')),
    path('', views.home , name= 'home'),

]

users/urls.py
from . import views
from django.urls import path

app_name= 'users'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('delete/', views.delete, name ='delete'),
    path('update/<int:id>/', views.update, name ='update'),
    path('user_follow/<int:id>/', views.user_follow, name='user_follow'),
    path('follow_view/', views.follow_view, name='follow_view'),

    

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(verbose_name = "email", max_length = 255, unique = True)
    username = models.CharField(max_length=30)
    nickname = models.CharField(max_length=50, blank=True)
    profile_image = models.ImageField(default="default.png", upload_to="profile_images/")
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    follow = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='followee')

users/views.py
import profile
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import User
from django.contrib.auth import authenticate, login as loginsession
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password


# Create your views here.
def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html')
    elif request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        passwordcheck = request.POST.get('passwordcheck')
        nickname = request.POST.get('nickname')
        if password == passwordcheck:
            User.objects.create_user(email=email, password=password, nickname=nickname, username=username)
            return render(request, 'login.html')
        else:

            return HttpResponse("비밀번호가 틀렸습니다.")
    
def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, email=email , password=password)
        if user is not None:
            loginsession(request, user)
            return redirect('/')
        else:
            return render(request, 'login.html', {'error':'이메일 인증 or 이메일 패스워드를 확인해 주세요!'})

@login_required
def logout(request):
        auth.logout(request)
        return redirect('users:login')

@login_required
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        logout(request)
    return render(request, 'login.html')


def update(request ,id):
    if request.method == "GET":
        return render(request, 'profile.html')
    elif request.method == "POST":
        user = User.objects.get(id=id)
        user.email = request.POST.get("email")
        user.username = request.POST.get("username")
        user.nickname = request.POST.get("nickname")
        origin_password = request.POST["origin_password"]
        check = check_password(origin_password, user.password)
        if check:
            new_password = request.POST["new_password"]
            user.set_password(new_password)
            user.save()
            return redirect("/")
@login_required
def user_follow(request, id):
    me = request.user
    click_user = User.objects.get(id=id)
    if me in click_user.followee.all():
        click_user.followee.remove(request.user)
    else:
        click_user.followee.add(request.user)
    return redirect(request.META['HTTP_REFERER'])   
    


@login_required
def follow_view(request): #
    if request.method == 'GET':
        user_list = User.objects.all().exclude(email=request.user.email)
        return render(request, 'follow.html',{"user_list":user_list})






    

users/templates/follow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>팔로우리스트페이지</title>
</head>
<body>
    <h1 팔로우 리스트></h1>
    {% for person in user_list %}
    <h2 class="card-title">{{ person.username }}</h2>
    <h3 class="card-subtitle mb-2 text-muted">{{ person.email }}</h3>
    팔로잉 {{ person.follow.count}} 명 / 팔로워 {{ person.followee.count }} 명
    {% if person in user.follow.all %}
    <a href= "{% url 'users:user_follow' person.id %}">[팔로우 취소]</a>
    {% else %}
    <a href= "{% url 'users:user_follow' person.id %}">[팔로우]</a>
    {% endif %}
    {% endfor %}
    
</body>
</html>

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인페이지</title>
</head>
<body>
    <form method="POST" action="{% url "users:login"  %}">
        {% csrf_token %}
        <input type = 'text' name = 'email' placeholder="email"/>
        <input type = 'password' name = 'password' placeholder="password" />
        <input type = 'submit'/>


    </form>

    
</body>
</html>

users/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원정보변경</title>
</head>
<body>
    <form action="{% url 'users:update' user.id %}" method="POST">
        {% csrf_token %}
          <div>
            이메일 : <input type="email" id="email" name="email" value="{{ user.email }}">
          </div>
          <div>
            이름 : <input type="text" id="name" name="username" value="{{ user.username }}"> 
          </div>
          <div>
            닉네임 : <input type="text" name="nickname" value="{{ user.nickname }}">
          </div>
          <div>
            기존 비밀번호 : <input type="password" name="origin_password">
          </div>
          <div>
            새 비밀번호 : <input type="text" name="new_password">
          </div>
          <button type="submit" class="btn btn-primary">수정하기</button>
      </form>
    
</body>
</html>

users/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입페이지</title>
</head>
<body>
    <form method="POST" action="{% url "users:signup"  %}">
        {% csrf_token %}
        <input type = 'text' name = 'email' placeholder="email"/>
        <input type = 'password' name = 'password' placeholder="password" />
        <input type = 'password' name = 'passwordcheck' placeholder="passwordcheck" />
        <input type = 'text' name = 'username' placeholder="username" />
        <input type = 'text' name = 'nickname' placeholder="nickname" />
        <input type = 'submit'/>


    </form>
    
</body>
</html>