contents/urls.py
from django.urls import path
from . import views

app_name='contents'
urlpatterns = [
    path("post/", views.post,name="post"),
    path("postdelete/<int:id>", views.postdelete, name="postdelete"),
    path("postupdate/<int:id>", views.postupdate, name="postupdate"),
    path('comment/<int:id>',views.write_comment, name='write_comment'),
    path('comment/delete/<int:id>',views.comment_delete, name='comment_delete'),
    path("like/<int:id>", views.like,name="like"),


 ]

django_project/urls.py
from . import views

"""django_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('contents/', include('contents.urls')),
    path('', views.home , name= 'home'),

]

users/urls.py
from . import views
from django.urls import path

app_name= 'users'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('delete/', views.delete, name ='delete'),
    path('update/<int:id>/', views.update, name ='update'),
    path('user_follow/<int:id>/', views.user_follow, name='user_follow'),
    path('follow_view/', views.follow_view, name='follow_view'),

    

]

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>홈페이지</title>
</head>
<body>
    <br>
     {{ user.email }}
     {{ user.nickname }}
     {{ user.username }}
     <br>
    <br>
    <a href = "{% url "users:logout" %}">로그아웃</a>
    <a href = "{% url "users:delete" %}">회원탈퇴</a>
    <a href = "{% url "users:update" user.id %}">내정보변경</a>
    <a href = "{% url "contents:post" %}">게시글작성하러가기</a>
    <br>
    <br>
    {% for post in posts %}
    <br>
    {{ post.title }}
    {{ post.content }}
    <br>
    {% for comment in post.comment%}
    <br>
    {{ comment.user.email }}
    {{ comment.content }}
    <br>
    {% if request.user == comment.user %}
    <button onclick="location.href='{% url "contents:comment_delete" comment.id %}'" >삭제</button
    {% endif %}
    <br>
    {% endfor %}
    <br>
    <form method="POST" action="{% url "contents:write_comment" post.id %}">
        {% csrf_token %}
        <div> 내용:<textarea name="content"></textarea>
        </div>
        <button type = "submit">댓글입력</button>
    </form>




    <a href="{% url 'contents:postdelete' post.id %}">게시글삭제</a>
    <a href="{% url 'contents:postupdate' post.id %}">게시글수정</a>
    좋아요 {{ post.like_authors.count }} 명
    <a href="{% url 'contents:like' post.id %}">좋아요</a>

    <br>
    {% endfor %}
    <br>
    <a href="{% url 'users:follow_view' %}">팔로우하러가기</a>
    



    
    
</body>
</html>